function añadircontacto(identificacion, nombre, apellidos, telefono, correo, ciudad, direccion){
    const contacto ={
        identificacion:identificacion,
        nombre:nombre,
        apellidos:apellidos,
        telefono:telefono,
        correo:correo,
        ciudad:ciudad,
        direccion:direccion,



    }
}

let contacto1={
    identificacion: "1",
    nombre:"edwin",
    apellido:"leyva",
    telefono:"15565468",
    correo:"asd@gmail.com",
    ciudad:"barranquilla",
    direccion:"cra 15 con 19"


};
let contacto2 = {
    identificacion: "2",
    nombre: "grace",
    apellido: "rodriguez",
    telefono: "5416564",
    correo: "poi@gmail.com",
    ciudad: "barranquilla",
    direccion: "cra 14 con 13",
};
let contacto3 = {
    identificacion: "1",
    nombre: "mary",
    apellido: "leyva",
    telefono: "8576542",
    correo: "meme@gmail.com",
    ciudad: "toronto",
    direccion: "cra 4 con 19",
};
let contacto4 = {
    identificacion: "1",
    nombre: "isaac",
    apellido: "leyva",
    telefono: "15565468",
    correo: "master@gmail.com",
    ciudad: "quebec",
    direccion: "cra 8 con 152",
};

push(contacto);